import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ar';
export type Direction = 'ltr' | 'rtl';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getLocalizedField: (data: any, field: string) => string;
}


const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Static translations for UI elements
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About Us',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.iso_certificate': 'ISO Certificate',
    
    // Common
    'common.loading': 'Loading...',
    'common.search': 'Search...',
    'common.view_details': 'View Details',
    'common.read_more': 'Read More',
    'common.contact_us': 'Contact Us',
    'common.get_quote': 'Get Quote',
    'common.learn_more': 'Learn More',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.product' :'No products found matching your criteria.',
    
    // Home page
    'home.hero.title': 'Al-Shmaly Agro – Quality Speaks',
    'home.hero.subtitle': 'We export the best of Syrian nature to the world, bringing authenticity and premium quality to your table.',
    'home.hero.explore_products': 'Explore Our Products',
    'home.about.1': 'Trusted by',
    'home.about.2': '5000+ Clients',
    'home.about.title': 'We bring authenticity into your world',
    'home.about.description': 'For over 27 years, Al-Shmaly has been the trusted name in exporting high-quality Syrian agricultural products. our commitment to quality and authenticity has made us the preferred partner for traders around the world, offering the finest legumes, spices, oils, and herbs from Syrian soil to tables across the globe.',

    'home.products.title': 'Featured Products',
    'home.services.title': 'Our Services',
    'home.blog.title': 'Latest News & Updates',
    
    // Products
    'products.title': 'Our Products',
    'products.all_categories': 'All Products',
    'products.no_products': 'No products found matching your criteria.',
    'products.weight_by': 'Weight',
    'products.weight': 'All Weight',
    'products.sort_by': 'Sort By',
    'products.sort.name': 'Name',
    'products.sort.price_low': 'Price: Low to High',
    'products.sort.price_high': 'Price: High to Low',
    'products.filters.title': 'Filters',
  'products.filters.search.label': 'Search Products',
  'products.filters.search.placeholder': 'Search products...',
  'products.filters.categories.label': 'Categories',
    'products.filt': 'All Products',
     'erorr':'Error loading products:',
    
    // About
    'about.title': 'About Al-Shmaly Agro ',
    'about.hero.subtitle': 'For over 27 years, we have been the bridge between Syrian agricultural heritage and global markets, bringing authentic, premium-quality products to tables worldwide.',
    'about.vision.title': 'Our Vision & Values',
    'about.vision.description.1': 'At Al-Shmaly , we believe that quality speaks for itself. Our mission is to preserve and share the rich agricultural heritage of Syria while building sustainable partnerships that benefit farmers, traders, and consumers worldwide.',
'about.vision.description.2': 'We are committed to maintaining the highest standards of quality, authenticity, and customer service in everything we do. Our products carry the essence of Syrian soil and the dedication of generations of farmers.',

    'about.journey.title': 'Our Journey',
    'about.global_reach.title': 'Global Reach',
    'about.global_reach.subtitle': 'We proudly export to over 30 countries worldwide, bringing Syrian agricultural excellence to global markets',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.get_in_touch': 'Get in Touch',
    'contact.send_message': 'Send us a Message',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.phone.1': 'Syria: +963 956 556 410',
    'contact.phone.2': 'Turkey : +90 538 687 6411',
    'contact.email': 'Email',
    'contact.business_hours': 'Business Hours',
    
    // Blog
    'blog.title': 'Al-Shmaly  Blog',
    'blog.subtitle': 'Stay updated with our latest news, insights, and stories from the world of Syrian agriculture',
    'blog.all_categories': 'All',
    'blog.no_posts': 'No blog posts found in this category.',
    'blog.load_more': 'Load More Articles',
    'blog.share': 'Share Article',
    'back.blog': 'Back to Blog',
    'No.related': 'No related articles found.',
    'Related.Articles': 'Related Articles',
    'Photo.Gallery': 'Photo Gallery',
    
    // Footer
    'footer.description': 'We export the best of Syrian nature to the world, bringing authenticity and quality to your table.',
    'footer.quick_links': 'Quick Links',
    'footer.contact_info': 'Contact Info',
    'footer.contact_adress':'Idlib, Sarmada, Syria',
    'footer.follow_us': 'Follow Us',
    'footer.rights': 'All rights reserved.',
    
    // About page
    'about.hero.subtitle': 'For over 27 years, we have been the bridge between Syrian agricultural heritage and global markets, bringing authentic, premium-quality products to tables worldwide.',
    'about.vision.title': 'Our Vision & Values',
    'about.vision.content': 'Under the leadership of the founder and general manager, Hassan Al Mohammad (Al-Shmaly), we maintain the highest standards in every product we export, ensuring authenticity and premium quality.',
    'about.journey.title': 'Our Journey',
    'about.journey.subtitle': 'Discover the milestones that have shaped our commitment to quality and excellence',
    'about.values.quality.title': 'Quality Excellence',
    'about.values.quality.description': 'We maintain the highest standards in every product we export, ensuring authenticity and premium quality.',
    'about.values.customer.title': 'Customer Focus',
    'about.values.customer.description': 'Our customers are at the heart of everything we do. We build lasting partnerships based on trust and reliability.',
    'about.values.global.title': 'Global Reach',
    'about.values.global.description': 'We connect Syrian agricultural heritage with global markets, bringing authentic flavors worldwide.',
    'about.values.sustainability.title': 'Sustainability',
    'about.values.sustainability.description': 'We are committed to sustainable farming practices that support local communities and the environment.',
    
    // Contact page
    'contact.hero.subtitle': 'Ready to start your journey with premium Syrian agricultural products? Get in touch with our team today.',
    'contact.get_in_touch': 'Get in Touch',
    'contact.send_message': 'Send us a Message',
    'contact.form.full_name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.placeholder.name': 'Your full name',
    'contact.form.placeholder.email': 'your.email@example.com',
    'contact.form.placeholder.phone': 'your number ',
    'contact.form.placeholder.message': 'Tell us about your requirements, questions, or how we can help you...',
    'contact.form.success': 'Thank you for your message! We will get back to you soon.',
    'contact.form.error': 'Failed to send message. Please try again.',
    'contact.location': 'Our Location',
    'contact.whatsapp': 'WhatsApp Chat',
    'contact.call_now': 'Call Now',
    'contact.business_hours.title': 'Business Hours',
    'contact.business_hours.weekdays': 'Saturday to Thursday: 9:00 AM – 5:00 PM',
    'contact.business_hours.friday': 'Friday: Closed',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.subtitle': 'Quick answers to common questions about our products and services',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'From packaging to delivery, we provide comprehensive solutions for your agricultural product needs',
    'services.packaging.title': 'Packaging & Filling',
    'services.packaging.description': 'Professional packaging solutions with custom labeling options',
    'services.shipping.title': 'Shipping & Export',
    'services.shipping.description': 'Worldwide shipping with reliable logistics partners',
    'services.wholesale.title': 'Wholesale Supply',
    'services.wholesale.description': 'Complete documentation and customs clearance support',
    'services.consulting.title': 'Agricultural Consulting',
    'services.consulting.description': 'Expert consulting services for traders and distributors',
    
    // General buttons and actions
    'buttons.explore_products': 'Explore Our Products',
    'buttons.browse_all_articles': 'Browse All Articles',
    'buttons.explore_all_products': 'Explore All Products',
    'buttons.contact_supplier': 'Contact Supplier',
    'buttons.request_quote': 'Request Quote',
    'buttons.load_more': 'Load More',
    
    // Marquee section
    'marquee.natural': '100% Natural',
    'marquee.quality_standards': 'Global Quality Standards',
    'marquee.years_expertise': '27+ Years of Expertise',
    'marquee.customer_satisfaction': 'Customer Satisfaction First',
    'marquee.trader_support': 'Ongoing Trader Support',
    
    // Statistics
    'statistics.satisfied_clients': 'Satisfied Clients',
    'statistics.exporting_countries': 'Exporting Countries',
    'statistics.years_experience': 'Years of Experience',
    
    // Timeline
    'timeline.foundation.title': 'Company Foundation',
    'timeline.foundation.description': 'Al-Shmaly  was established in Idlib, Syria, with a vision to export premium Syrian agricultural products.',
    'timeline.first_export.title': 'First International Export',
    'timeline.first_export.description': 'Successfully exported our first shipment of freekeh and legumes to European markets.',
    'timeline.certifications.title': 'Quality Certifications',
    'timeline.certifications.description': 'Obtained ISO 9001 and ISO 22000 certifications and implemented modern Sortex cleaning technology.',
    'timeline.export_launch.title': 'Export Expansion',
    'timeline.export_launch.description': 'Started exporting through Souqna First Gate in Qatar, gradually expanding to other countries with a product range exceeding 30 items.',
    'timeline.sustainable_future.title': 'Sustainable Future',
    'timeline.sustainable_future.description': 'Committed to sustainable farming practices and supporting local Syrian farmers.',
    
    // FAQ
    'faq.minimum_order.question': 'What is your minimum order quantity?',
    'faq.minimum_order.answer': 'Our minimum order quantity varies by product. For most items, it\'s 1 ton, but we can accommodate smaller orders for sample testing.',
    'faq.certificates.question': 'Do you provide certificates of origin and quality?',
    'faq.certificates.answer': 'Yes, we provide all necessary documentation including certificates of origin, quality certificates, and phytosanitary certificates for international shipping.',
    'faq.payment_terms.question': 'What are your payment terms?',
    'faq.payment_terms.answer': 'We accept various payment methods including T/T, L/C, and other internationally recognized payment terms. Specific terms can be discussed based on order size and relationship.',
    'faq.shipping_time.question': 'How long does shipping take?',
    'faq.shipping_time.answer': 'Shipping times vary by destination. Typically, it takes 2-4 weeks for sea freight and 3-7 days for air freight to most international destinations.',
    'faq.private_labeling.question': 'Do you offer private labeling services?',
    'faq.private_labeling.answer': 'Yes, we offer private labeling services with your brand. We can customize packaging design and labeling according to your specifications.',
    
    // About page
    'about.established': 'Established',
    
    // Contact location
    'contact.location.industrial_zone': 'Industrial Zone',
    'contact.location.full_address': 'Idlib, Sarmada, Syria',
         'Note':'Note:',
     'note.all':'Note: For international clients, we provide comprehensive shipping and logistics support. Our team will coordinate with you to ensure smooth delivery to your location.',
    
    // Footer sections
    'footer.company_description': 'We export the best of Syrian nature to the world, bringing authenticity and quality to your table.',
    'footer.made_by': 'Designed by',
    'footer.all_rights': 'All rights reserved.',
    'footer.rights':'© 2025 Al-Shmaly  Agricultural Products.',
    
    // Form validation
    'validation.required': 'This field is required',
    'validation.email': 'Please enter a valid email address',
    'validation.phone': 'Please enter a valid phone number',
    
    // Misc
    'misc.established': 'Established',
    'misc.trusted_by': 'Trusted by',
    'misc.clients': 'Clients',
    'misc.years_experience': 'Years of Experience',
    'misc.exporting_countries': 'Exporting Countries',
    'misc.satisfied_clients': 'Satisfied Clients',
    'misc.industrial_zone': 'Industrial Zone',
    'misc.select_subject': 'Select a subject',
    'misc.subject_options.product_inquiry': 'Product Inquiry',
    'misc.subject_options.bulk_order': 'Bulk Order',
    'misc.subject_options.partnership': 'Partnership Opportunity',
    'misc.subject_options.quality_question': 'Quality Question',
    'misc.subject_options.shipping': 'Shipping & Logistics',
    'misc.subject_options.other': 'Other',
    
    // Products
    'products.packaging_options': 'Packaging Options',
    'products.additional_info': 'Additional Information',
    'products.specifications': 'Specifications',
    'products.related_products': 'Related Products',
    'products.discover': 'Discover our premium Syrian agricultural products, carefully selected and processed to bring you the authentic taste of Syria.',
    'back': 'Back to Products',
    'products.show': 'Showing ',
     'products.show2': 'products ',
    'common.loading': 'Loading...',
   'categories.all': 'All categories',
   'pagination.previous':'previous',
    'pagination.next':' next',
    'login.title': 'Admin Dashboard',
  'login.subtitle': 'Sign in to manage your content',
  'login.emailLabel': 'Email Address',
  'login.emailPlaceholder': 'admin@al-shmaly.com',
  'login.passwordLabel': 'Password',
  'login.passwordPlaceholder': 'Enter your password',
  'login.signIn': 'Sign In',
  'login.error': 'Login failed',
    'admin.image': 'Image',
'admin.management': 'Management',
'admin.upload': 'Upload',
'admin.drag_drop_images': 'Drag & drop images here',
'admin.or_click_to_browse': 'Or click to browse files',
'admin.uploaded_images': 'Uploaded Images',
'admin.clear_all': 'Clear All',
'admin.remove': 'Remove',
'admin.alt_text': 'Alt Text',

'blog.featured_image': 'Featured Image',
'blog.featured_selected': 'Featured image selected',
'blog.will_be_shown_in_preview': 'This image will be shown in the preview',
'blog.featured': 'Featured',
'blog.set_featured': 'Set as Featured',
'blog.no_images': 'No images',
'blog.upload_images_to_get_started': 'Upload images to get started',


  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.products': 'المنتجات',
    'nav.about': 'من نحن', 
    'nav.blog': 'المدونة',
    'nav.contact': 'اتصل بنا',
    'nav.iso_certificate': 'شهادة الآيزو',
    'admin.image': 'صورة',
'admin.management': 'إدارة',
'admin.upload': 'رفع',
'admin.drag_drop_images': 'اسحب وأفلت الصور هنا',
'admin.or_click_to_browse': 'أو اضغط لاختيار الملفات',
'admin.uploaded_images': 'الصور المرفوعة',
'admin.clear_all': 'مسح الكل',
'admin.remove': 'حذف',
'admin.alt_text': 'النص البديل',

'blog.featured_image': 'الصورة المميزة',
'blog.featured_selected': 'تم تحديد الصورة المميزة',
'blog.will_be_shown_in_preview': 'ستظهر هذه الصورة في المعاينة',
'blog.featured': 'مميز',
'blog.set_featured': 'تعيين كمميز',
'blog.no_images': 'لا توجد صور',
'blog.upload_images_to_get_started': 'قم برفع الصور للبدء',

    // Common
    'common.loading': 'جارٍ التحميل...',
    'common.search': 'البحث...',
    'common.view_details': 'عرض التفاصيل',
    'common.read_more': 'اقرأ المزيد',
    'common.contact_us': 'اتصل بنا',
    'common.get_quote': 'احصل على عرض سعر',
    'common.learn_more': 'تعلم المزيد',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.submit': 'إرسال',
    'common.close': 'إغلاق',
    'common.product':'لا يوجد منتجات مطابقة ',
  
    
    
    // Home page
    'home.hero.title': 'مؤسسة الشمالي  التجارية– الجودة تتحدث عن نفسها',
    'home.hero.subtitle': 'نصدر أفضل ما في الطبيعة السورية إلى العالم، ونقدم الأصالة والجودة المميزة لمائدتك.',
    'home.hero.explore_products': 'استكشف منتجاتنا',
    'home.about.title': 'نحن نجلب الأصالة إلى عالمك',
    'home.about.1': 'موثوق من قبل',
    'home.about.2': 'أكثر من 5000 عميل',
   'home.about.description': 'لأكثر من 27 عامًا، كانت الشمالي الاسم الموثوق في تصدير المنتجات الزراعية السورية عالية الجودة. جعلنا التزامنا بالجودة والأصالة الشريك المفضل للتجار حول العالم، حيث نُقدِّم أفضل أنواع البقوليات، والتوابل، والزيوت، والأعشاب من الأرض السورية إلى موائد العالم.',
    'home.products.title': 'المنتجات المميزة',
    'home.services.title': 'خدماتنا',
    'home.blog.title': 'آخر الأخبار والتحديثات',
    
    // Products
    'products.title': 'منتجاتنا',
    'products.all_categories': 'جميع المنتجات',
    'products.no_products': 'لم يتم العثور على منتجات تطابق معاييرك.',
     'products.weight_by': 'الوزن',
      'products.weight':  'كل الأحجام ',
    'products.sort_by': 'ترتيب حسب',
    'products.sort.name': 'الاسم',
    'products.sort.price_low': 'السعر: من الأقل إلى الأعلى',
    'products.sort.price_high': 'السعر: من الأعلى إلى الأقل',
    'products.filters.title': 'الفلاتر',
  'products.filters.search.label': 'ابحث في المنتجات',
  'products.filters.search.placeholder': 'ابحث عن المنتجات...',
  'products.filters.categories.label': 'التصنيفات',
    'products.show': 'عرض',
'products.show2': 'منتجاً',
    'common.loading': 'جارٍ التحميل...',
    'products.filt': 'كل المنتجات',
     'pagination.previous':'الصفحة السابقة',
    'pagination.next':'الصفحة التالية',
     'erorr':'لا يمكن الوصول للمنتجات ',
    
    // About
    'about.title': 'عن  مؤسسة الشمالي',
    'about.hero.subtitle': 'لأكثر من 27 عامًا، كنا الجسر بين التراث الزراعي السوري والأسواق العالمية، نجلب منتجات أصلية عالية الجودة إلى موائد العالم.',
    'about.vision.title': 'رؤيتنا وقيمنا',
 'about.vision.description.1': 'في الشمالي، نؤمن بأن الجودة تتحدث عن نفسها. تتمثل مهمتنا في الحفاظ على التراث الزراعي الغني في سوريا ومشاركته، مع بناء شراكات مستدامة تعود بالفائدة على المزارعين والتجار والمستهلكين حول العالم.',
'about.vision.description.2': 'نحن ملتزمون بالحفاظ على أعلى معايير الجودة والأصالة وخدمة العملاء في كل ما نقوم به. منتجاتنا تحمل جوهر الأرض السورية وتفاني أجيال من المزارعين.',
    'about.journey.title': 'رحلتنا',
    'about.global_reach.title': 'الوصول العالمي',
    'about.global_reach.subtitle': 'نفخر بالتصدير إلى أكثر من 30 دولة حول العالم، نجلب التميز الزراعي السوري إلى الأسواق العالمية',
    
    // Contact 
    'contact.title': 'اتصل بنا',
    'contact.get_in_touch': 'تواصل معنا',
    'contact.send_message': 'أرسل لنا رسالة',
    'contact.address': 'العنوان',
    'contact.phone': 'الهاتف',
    'contact.phone.1': 'سوريا : \u200E+963 956 556 410\u200E',
    'contact.phone.2': 'تركيا : \u200E+90 538 687 6411\u200E',
    'contact.email': 'البريد الإلكتروني',
    'contact.business_hours': 'ساعات العمل',

    
    // Blog
    'blog.title': 'مدونة الشمالي',
    'blog.subtitle': 'ابق على اطلاع بآخر أخبارنا ورؤانا وقصصنا من عالم الزراعة السورية',
    'blog.all_categories': 'الكل',
    'blog.no_posts': 'لم يتم العثور على مقالات في هذه الفئة.',
    'blog.load_more': 'تحميل المزيد من المقالات',
    'blog.share': 'مشاركة المقال',
    'back.blog': 'العودة إلى المدونة',
     'No.related': 'لا يوجد مقالات مرتبطة ',
    'Related.Articles': 'المقالات المرتبطة',
    'Photo.Gallery': 'معرض الصور',
    // Footer
    'footer.description': 'نصدر أفضل ما في الطبيعة السورية إلى العالم، ونجلب الأصالة والجودة إلى مائدتك.',
    'footer.quick_links': 'روابط سريعة',
    'footer.contact_info': 'معلومات الاتصال',
     'footer.contact_adress':'إدلب، سرمدا، سوريا',
    'footer.follow_us': 'تابعنا',
    'footer.rights': 'جميع الحقوق محفوظة.',
    
    // About page
    'about.hero.subtitle': 'لأكثر من 27 عامًا، كنا الجسر بين التراث الزراعي السوري والأسواق العالمية، نجلب منتجات أصلية عالية الجودة إلى موائد العالم.',
    'about.vision.title': 'رؤيتنا وقيمنا',
    'about.vision.content': 'تحت قيادة المؤسس والمدير العام، حسن الشمالي، نلتزم بأعلى معايير الجودة في كل منتج نقوم بتصديره، بما يضمن الأصالة والجودة الفاخرة.',
    'about.journey.title': 'رحلتنا',
    'about.journey.subtitle': 'اكتشف المعالم التي شكلت التزامنا بالجودة والتميز',
    'about.values.quality.title': 'التميز في الجودة',
    'about.values.quality.description': 'نحافظ على أعلى المعايير في كل منتج نصدره، مما يضمن الأصالة والجودة المتميزة.',
    'about.values.customer.title': 'التركيز على العملاء',
    'about.values.customer.description': 'عملاؤنا في قلب كل ما نفعله. نبني شراكات دائمة قائمة على الثقة والموثوقية.',
    'about.values.global.title': 'الوصول العالمي',
    'about.values.global.description': 'نربط التراث الزراعي السوري بالأسواق العالمية، ونقدم النكهات الأصلية في جميع أنحاء العالم.',
    'about.values.sustainability.title': 'الاستدامة',
    'about.values.sustainability.description': 'نحن ملتزمون بممارسات الزراعة المستدامة التي تدعم المجتمعات المحلية والبيئة.',
    
    // Contact page
    'contact.hero.subtitle': 'هل أنت مستعد لبدء رحلتك مع المنتجات الزراعية السورية المتميزة؟ تواصل مع فريقنا اليوم.',
    'contact.get_in_touch': 'تواصل معنا',
    'contact.send_message': 'أرسل لنا رسالة',
    'contact.form.full_name': 'الاسم الكامل',
    'contact.form.email': 'عنوان البريد الإلكتروني',
    'contact.form.phone': 'رقم الهاتف',
    'contact.form.subject': 'الموضوع',
    'contact.form.message': 'الرسالة',
    'contact.form.send': 'إرسال الرسالة',
    'contact.form.sending': 'جارٍ الإرسال...',
    'contact.form.placeholder.name': 'اسمك الكامل',
    'contact.form.placeholder.email': 'your.email@example.com',
    'contact.form.placeholder.phone': 'رقمك',
    'contact.form.placeholder.message': 'أخبرنا عن متطلباتك أو أسئلتك أو كيف يمكننا مساعدتك...',
    'contact.form.success': 'شكرًا لك على رسالتك! سنعود إليك قريبًا.',
    'contact.form.error': 'فشل في إرسال الرسالة. يرجى المحاولة مرة أخرى.',
    'contact.location': 'موقعنا',
    'contact.whatsapp': 'محادثة واتساب',
    'contact.call_now': 'اتصل الآن',
    'contact.business_hours.title': 'ساعات العمل',
    'contact.business_hours.weekdays': 'السبت إلى الخميس: 9:00 صباحًا – 5:00 مساءً',
    'contact.business_hours.friday': 'الجمعة: مغلق',
    'contact.faq.title': 'الأسئلة الشائعة',
    'contact.faq.subtitle': 'إجابات سريعة على الأسئلة الشائعة حول منتجاتنا وخدماتنا',
    
    // Services
    'services.title': 'خدماتنا',
    'services.subtitle': 'من التعبئة إلى التسليم، نقدم حلولاً شاملة لاحتياجات منتجاتك الزراعية',
    'services.packaging.title': 'التعبئة والتغليف',
    'services.packaging.description': 'حلول تعبئة احترافية مع خيارات وضع العلامات المخصصة',
    'services.shipping.title': 'الشحن والتصدير',
    'services.shipping.description': 'الشحن في جميع أنحاء العالم مع شركاء لوجستيين موثوقين',
    'services.wholesale.title': 'التوريد بالجملة',
    'services.wholesale.description': 'وثائق كاملة ودعم إجراءات الجمارك',
    'services.consulting.title': 'الاستشارات الزراعية',
    'services.consulting.description': 'خدمات استشارية متخصصة للتجار والموزعين',
    
    // General buttons and actions
    'buttons.explore_products': 'استكشف منتجاتنا',
    'buttons.browse_all_articles': 'تصفح جميع المقالات',
    'buttons.explore_all_products': 'استكشف جميع المنتجات',
    'buttons.contact_supplier': 'اتصل بالمورد',
    'buttons.request_quote': 'طلب عرض سعر',
    'buttons.load_more': 'تحميل المزيد',
    
    // Marquee section
    'marquee.natural': '100% طبيعي',
    'marquee.quality_standards': 'معايير الجودة العالمية',
    'marquee.years_expertise': '27+ سنة من الخبرة',
    'marquee.customer_satisfaction': 'رضا العملاء أولاً',
    'marquee.trader_support': 'دعم مستمر للتجار',
    
    // Statistics
    'statistics.satisfied_clients': 'العملاء الراضون',
    'statistics.exporting_countries': 'الدول المصدِّرة إليها',
    'statistics.years_experience': 'سنوات من الخبرة',
    
    // Timeline
    'timeline.foundation.title': 'تأسيس الشركة',
    'timeline.foundation.description': 'تأسست الشمالي في إدلب، سوريا، برؤية لتصدير المنتجات الزراعية السورية المتميزة.',
    'timeline.first_export.title': 'أول تصدير دولي',
    'timeline.first_export.description': 'نجحنا في تصدير أول شحنة من الفريكة والبقوليات إلى الأسواق الأوروبية.',
    'timeline.certifications.title': 'شهادات الجودة',
    'timeline.certifications.description': 'حصلنا على شهادات الآيزو 9001 و22000 وطبقنا تقنية التنظيف الحديثة Sortex.',
    'timeline.export_launch.title': 'توسيع التصدير',
    'timeline.export_launch.description': 'بدأنا التصدير عبر سوقنا البوابة الأولى في قطر، وتوسعنا تدريجياً إلى دول أخرى بمجموعة منتجات تتجاوز 30 صنفاً.',
    'timeline.sustainable_future.title': 'مستقبل مستدام',
    'timeline.sustainable_future.description': 'التزمنا بممارسات الزراعة المستدامة ودعم المزارعين السوريين المحليين.',
    
    // FAQ
    'faq.minimum_order.question': 'ما هي الكمية الدنيا للطلب؟',
    'faq.minimum_order.answer': 'تختلف الكمية الدنيا للطلب حسب المنتج. بالنسبة لمعظم الأصناف، هي طن واحد، لكن يمكننا استيعاب طلبات أصغر لأغراض اختبار العينات.',
    'faq.certificates.question': 'هل تقدمون شهادات المنشأ والجودة؟',
    'faq.certificates.answer': 'نعم، نقدم جميع الوثائق اللازمة بما في ذلك شهادات المنشأ وشهادات الجودة والشهادات النباتية للشحن الدولي.',
    'faq.payment_terms.question': 'ما هي شروط الدفع لديكم؟',
    'faq.payment_terms.answer': 'نقبل طرق دفع متنوعة بما في ذلك T/T و L/C وشروط دفع دولية أخرى معترف بها. يمكن مناقشة الشروط المحددة بناءً على حجم الطلب والعلاقة.',
    'faq.shipping_time.question': 'كم من الوقت يستغرق الشحن؟',
    'faq.shipping_time.answer': 'تختلف أوقات الشحن حسب الوجهة. عادة، يستغرق 2-4 أسابيع للشحن البحري و3-7 أيام للشحن الجوي إلى معظم الوجهات الدولية.',
    'faq.private_labeling.question': 'هل تقدمون خدمات العلامة التجارية الخاصة؟',
    'faq.private_labeling.answer': 'نعم، نقدم خدمات العلامة التجارية الخاصة بعلامتكم التجارية. يمكننا تخصيص تصميم التعبئة ووضع العلامات وفقاً لمواصفاتكم.',
    
    // About page
    'about.established': 'تأسست عام',
    
    // Contact location
    'contact.location.industrial_zone': 'المنطقة الصناعية',
    'contact.location.full_address': 'إدلب، سرمدا، سوريا',
    'Note':'ملاحظة:',
    'note.all':'ملاحظة: للعملاء الدوليين، نوفر دعمًا شاملاً في الشحن والخدمات اللوجستية. سيقوم فريقنا بالتنسيق معكم لضمان توصيل سلس إلى موقعكم.',
    
    // Footer sections
    'footer.company_description': 'نصدر أفضل ما في الطبيعة السورية إلى العالم، ونجلب الأصالة والجودة إلى مائدتك.',
    'footer.made_by': 'تم التطوير بواسطة',
    'footer.all_rights': 'جميع الحقوق محفوظة.',
    'footer.rights':'© 2025 المنتجات الزراعية الشمالي',
    
    // Form validation
    'validation.required': 'هذا الحقل مطلوب',
    'validation.email': 'يرجى إدخال عنوان بريد إلكتروني صحيح',
    'validation.phone': 'يرجى إدخال رقم هاتف صحيح',
    
    // Misc
    'misc.established': 'تأسست عام',
    'misc.trusted_by': 'موثوق من قبل',
    'misc.clients': 'عميل',
    'misc.years_experience': 'سنوات من الخبرة',
    'misc.exporting_countries': 'دولة مصدرة إليها',
    'misc.satisfied_clients': 'عميل راضٍ',
    'misc.industrial_zone': 'المنطقة الصناعية',
    'misc.select_subject': 'اختر موضوعًا',
    'misc.subject_options.product_inquiry': 'استفسار عن المنتج',
    'misc.subject_options.bulk_order': 'طلب بالجملة',
    'misc.subject_options.partnership': 'فرصة شراكة',
    'misc.subject_options.quality_question': 'سؤال عن الجودة',
    'misc.subject_options.shipping': 'الشحن واللوجستيات',
    'misc.subject_options.other': 'أخرى',
    
    // Products
    'products.packaging_options': 'خيارات التعبئة',
    'products.additional_info': 'معلومات إضافية',
    'products.specifications': 'المواصفات',
    'products.related_products': 'منتجات ذات صلة',
    'products.discover': 'اكتشف منتجاتنا الزراعية السورية المتميزة، مختارة ومعالجة بعناية لنقدم لك الطعم الأصيل لسوريا.',
    'back': 'العودة إلى المنتجات',
     'categories.all': 'كل تصنيفات',
    'login.title': 'لوحة تحكم الإدارة',
  'login.subtitle': 'تسجيل الدخول لإدارة المحتوى الخاص بك',
  'login.emailLabel': 'البريد الإلكتروني',
  'login.emailPlaceholder': 'admin@al-shmaly.com',
  'login.passwordLabel': 'كلمة السر',
  'login.passwordPlaceholder': 'أدخل كلمة السر',
  'login.signIn': 'تسجيل الدخول',
  'login.error': 'فشل تسجيل الدخول',

  }
};

// Enhanced admin translations for specific pages
const adminTranslations = {
  en: {
    'admin.dashboard': 'Dashboard',
    'admin.products.management': 'Products Management',
     'admin.products.management2': 'Add Products ',
    'admin.categories.management': 'Categories Management',
    'admin.blog.management': 'Blog Management',
    'admin.contacts.management': 'Contacts Management',
    'admin.blog_categories.management': 'Blog Categories',
    'admin.homepage.management': 'Homepage Management',
    'admin.export_countries.management': 'Export Countries Management',
    'admin.dashboard.overview': 'Dashboard Overview',
    'admin.language.switch': 'Switch Language',
    'admin.language.current': 'Current Language',
    'admin.language.english': 'English',
    'admin.language.arabic': 'العربية',
    
    // Admin Interface
    'admin.products':'products',
    'add.to.homepage': 'Add to Homepage',
    'homepage.products': 'Homepage Products',
    'homepage.blog.posts': 'Homepage Blog Posts',
    'order': 'Order',
    'product': 'Product',
    'blog.post': 'Blog Post',
    'status': 'Status',
    'actions': 'Actions',
    'active': 'Active',
    'inactive': 'Inactive',
    'view.item': 'View Item',
    'remove.from.homepage': 'Remove from Homepage',
    'add.item.to.homepage': 'Add to Homepage',
    'search.products': 'Search products...',
    'search.blog': 'Search blog...',
    'no.available.products': 'No available products found.',
    'no.available.blog.posts': 'No available blog posts found.',
    'uncategorized': 'Uncategorized',
    'add': 'Add',
    'admin.add': 'Add',
    'admin.search': 'Search',
    'admin.all': 'All',
    'admin.category': 'Category',
    'admin.price': 'Price',
    'admin.availability': 'Availability',
    'admin.actions': 'Actions',
    'admin.uncategorized': 'Uncategorized',
    'admin.view': 'View',
    'admin.edit': 'Edit',
    'admin.manage': 'Manage',
    'admin.delete': 'Delete',
    'admin.basic_info': 'Basic Information',
    'admin.name': 'Name',
    'admin.english': 'English',
    'admin.arabic': 'Arabic',
    'admin.description': 'Description',
    'admin.select': 'Select',
    'admin.specifications': 'Specifications',
    'admin.image': 'Image',
    'admin.alt_text': 'Alt Text',
    'admin.order': 'Order',
    'admin.packages': 'Packages',
    'admin.weight': 'Weight',
    'admin.default': 'Default',
    'admin.cancel': 'Cancel',
    'admin.saving': 'Saving...',
    'admin.update': 'Update',
    'admin.create': 'Create',
    'admin.related': 'Related Products',
     'admin.related2': 'Related Blog',
    'admin.current': 'Current',
    'admin.no_data': 'No data available',
    'admin.similar': 'Similar',
    'admin.complementary': 'Complementary',
    'admin.product': 'Product',
    'admin.confirm_delete': 'Confirm Delete',
    'admin.delete_warning': "You won't be able to revert this!",
    
    'categories.title': 'Categories Management',
    'categories.add_category': 'Add Category',
    'categories.search_placeholder': 'Search categories...',
    'categories.table.name': 'Name',
    'categories.table.slug': 'Slug',
    'categories.table.description': 'Description',
    'categories.table.created': 'Created At',
    'categories.table.actions': 'Actions',
    'categories.form.add_title': 'Add Category',
    'categories.form.edit_title': 'Edit Category',
    'categories.form.name_en': 'Name (English)',
    'categories.form.name_ar': 'Name (Arabic)',
    'categories.form.slug': 'Slug',
    'categories.form.description_en': 'Description (English)',
    'categories.form.description_ar': 'Description (Arabic)',
    'categories.form.cancel': 'Cancel',
    'categories.form.saving': 'Saving...',
    'categories.form.update': 'Update',
    'categories.form.create': 'Create',
    'categories.delete_modal.title': 'Delete Confirmation',
    'categories.delete_modal.message': 'Are you sure you want to delete this category? This action cannot be undone.',
    'categories.delete_modal.cancel': 'Cancel',
    'categories.delete_modal.delete': 'Delete',
    'export.title': 'Export Countries',
  'export.add': 'Add Country',
  'export.search.placeholder': 'Search countries...',
  'export.table.order': 'Order',
  'export.table.country': 'Country',
  'export.table.exports': 'Annual Exports',
  'export.table.products': 'Main Products',
  'export.table.status': 'Status',
  'export.table.actions': 'Actions',
  'export.status.active': 'Active',
  'export.status.inactive': 'Inactive',
  'export.edit': 'Edit Country',
  'export.add_new': 'Add New Export Country',
  'export.name_en': 'Country Name (EN)',
  'export.name_ar': 'Country Name (AR)',
  'export.exports_en': 'Annual Exports (EN)',
  'export.exports_ar': 'Annual Exports (AR)',
  'export.products_en': 'Main Products (EN)',
  'export.products_ar': 'Main Products (AR)',
  'export.display_on_site': 'Display on website',
  'export.cancel': 'Cancel',
  'export.create': 'Create',
  'export.update': 'Update',
  'export.saving': 'Saving...',
  'export.delete.title': 'Delete Export Country',
  'export.delete.confirmation': 'Are you sure you want to delete this export country? This action cannot be undone.',
  'export.delete': 'Delete',
    'export.title': 'Export Countries',
  'export.add': 'Add Country',
  'export.search.placeholder': 'Search countries...',
  'export.table.order': 'Order',
  'export.table.country': 'Country',
  'export.table.exports': 'Annual Exports',
  'export.table.products': 'Main Products',
  'export.table.status': 'Status',
  'export.table.actions': 'Actions',
  'export.status.active': 'Active',
  'export.status.inactive': 'Inactive',
  'export.edit': 'Edit Country',
  'export.add_new': 'Add New Export Country',
  'export.name_en': 'Country Name (EN)',
  'export.name_ar': 'Country Name (AR)',
  'export.exports_en': 'Annual Exports (EN)',
  'export.exports_ar': 'Annual Exports (AR)',
  'export.products_en': 'Main Products (EN)',
  'export.products_ar': 'Main Products (AR)',
  'export.display_on_site': 'Display on website',
  'export.cancel': 'Cancel',
  'export.create': 'Create',
  'export.update': 'Update',
  'export.saving': 'Saving...',
  'export.delete.title': 'Delete Export Country',
  'export.delete.confirmation': 'Are you sure you want to delete this export country? This action cannot be undone.',
  'export.delete': 'Delete',
     'blog.title': 'Blog Posts Management',
  'blog.add_post': 'Add Post',
  'blog.search.placeholder': 'Search posts...',
  'blog.all_categories': 'All Categories',
  'blog.uncategorized': 'Uncategorized',
  'blog.table.post': 'Post',
  'blog.table.category': 'Category',
  'blog.table.author': 'Author',
  'blog.table.status': 'Status',
  'blog.table.date': 'Date',
  'blog.table.actions': 'Actions',
  'blog.status.published': 'Published',
  'blog.status.draft': 'Draft',
  'blog.modal.edit_post': 'Edit Post',
  'blog.modal.add_new_post': 'Add New Post',
  'blog.modal.select_category': 'Select Category',
  'blog.modal.cancel': 'Cancel',
  'blog.modal.saving': 'Saving...',
  'blog.modal.delete_title': 'Delete Post',
  'blog.modal.delete_confirmation': 'Are you sure you want to delete this blog post? This action cannot be undone.',
  'blog.modal.delete': 'Delete',
  'blog.modal.view_post': 'View Post',
  'blog.modal.edit_post_btn': 'Edit Post',
  'blog.modal.manage_related_posts': 'Manage Related Blog Posts',
  'blog.modal.related_posts': 'Current Related Posts',
  'blog.modal.add_related_posts': 'Add Related Posts',
  'blog.modal.no_related_posts': 'No related posts added yet.',
  'blog.modal.all_related': 'All available posts are already related.',
  'blog.fields.title_en': 'Title (EN)',
  'blog.fields.title_ar': 'Title (AR)',
  'blog.fields.slug': 'Slug',
  'blog.fields.excerpt_en': 'Excerpt (EN)',
  'blog.fields.excerpt_ar': 'Excerpt (AR)',
  'blog.fields.content_en': 'Content (EN)',
  'blog.fields.content_ar': 'Content (AR)',
  'blog.fields.category': 'Category',
  'blog.fields.author_en': 'Author (EN)',
  'blog.fields.author_ar': 'Author (AR)',
  'blog.fields.read_time_en': 'Read Time (EN)',
  'blog.fields.read_time_ar': 'Read Time (AR)',
  'blog.fields.event_date_en': 'Event Date (EN)',
  'blog.fields.event_date_ar': 'Event Date (AR)',
  'blog.fields.status': 'Status',
  'blog.fields.featured_image_url': 'Featured Image URL',
  'blog.relation_types.related': 'Related',
  'blog.relation_types.similar': 'Similar',
  'blog.relation_types.follow_up': 'Follow-up',
     'blogCategories.title': 'Blog Categories',
  'blogCategories.add': 'Add Category',
  'blogCategories.search.placeholder': 'Search blog categories...',
  'blogCategories.table.name': 'Name',
  'blogCategories.table.slug': 'Slug',
  'blogCategories.table.created': 'Created',
  'blogCategories.table.actions': 'Actions',
  'blogCategories.edit.title': 'Edit Blog Category',
  'blogCategories.addNew.title': 'Add New Blog Category',
  'blogCategories.form.name_en': 'Name (EN)',
  'blogCategories.form.name_ar': 'Name (AR)',
  'blogCategories.form.slug': 'Slug',
  'blogCategories.form.name_en.placeholder': 'Category name in English',
  'blogCategories.form.name_ar.placeholder': 'اسم الفئة بالعربية',
  'blogCategories.form.slug.placeholder': 'category-slug',
  'blogCategories.form.cancel': 'Cancel',
  'blogCategories.form.create': 'Create',
  'blogCategories.form.update': 'Update',
  'blogCategories.form.saving': 'Saving...',
  'blogCategories.delete.title': 'Delete Blog Category',
  'blogCategories.delete.confirmation': 'Are you sure you want to delete this blog category? This action cannot be undone.',
  'blogCategories.delete.cancel': 'Cancel',
  'blogCategories.delete.delete': 'Delete',
    'contacts.title': 'Contact Messages',
  'contacts.totalMessages': 'total messages',
  'contacts.search.placeholder': 'Search messages...',
  'contacts.filter.allStatus': 'All Status',
  'contacts.filter.unread': 'Unread',
  'contacts.filter.read': 'Read',
  'contacts.filter.responded': 'Responded',
  'contacts.table.contact': 'Contact',
  'contacts.table.subject': 'Subject',
  'contacts.table.status': 'Status',
  'contacts.table.date': 'Date',
  'contacts.table.language': 'Language',
  'contacts.table.actions': 'Actions',
  'contacts.status.unread': 'Unread',
  'contacts.status.read': 'Read',
  'contacts.status.responded': 'Responded',
  'contacts.language.ar': 'Arabic',
  'contacts.language.en': 'English',
  'contacts.action.viewDetails': 'View Details',
  'contacts.action.deleteMessage': 'Delete Message',
  'contacts.details.title': 'Contact Message Details',
  'contacts.details.name': 'Name',
  'contacts.details.email': 'Email',
  'contacts.details.phone': 'Phone',
  'contacts.details.subject': 'Subject',
  'contacts.details.message': 'Message',
  'contacts.details.status': 'Status',
  'contacts.details.dateReceived': 'Date Received',
  'contacts.details.close': 'Close',
  'contacts.details.reply': 'Reply via Email',
  'contacts.delete.title': 'Delete Contact Message',
  'contacts.delete.confirmation': 'Are you sure you want to delete this contact message? This action cannot be undone.',
  'contacts.delete.cancel': 'Cancel',
  'contacts.delete.delete': 'Delete',
     'admin.logout': 'Log out',
    'admin.welcome': 'Welcome',
    'admin.last_updated': 'last updated',
       'admin.logo': 'Al-Shmaly Agro ',
  },
  ar: {
    'admin.products.management': 'إدارة المنتجات',
    'admin.products.management2': 'إضافة منتجات',
    'admin.categories.management': 'إدارة الفئات',
    'admin.blog.management': 'إدارة المدونة',
    'admin.blog_categories.management': 'إدارة فئات المدونة',
    'admin.contacts.management': 'إدارة جهات الاتصال',
    'admin.homepage.management': 'إدارة الصفحة الرئيسية',
    'admin.export_countries.management': 'إدارة البلدان المصدرة',
    'admin.dashboard.overview': 'نظرة عامة على لوحة التحكم',
    'admin.language.switch': 'تبديل اللغة',
    'admin.language.current': 'اللغة الحالية',
    'admin.language.english': 'English',
    'admin.language.arabic': 'العربية',
    
    'add.to.homepage': 'اضافة لصفحة الرئيسية',
    'homepage.products': 'منتجات الصفحة الرئيسية',
    'homepage.blog.posts': 'مقالات المدونة في الصفحة الرئيسية',
    'order': 'الترتيب',
    'product': 'المنتج',
    'blog.post': 'مقال مدونة',
    'status': 'الحالة',
    'actions': 'الإجراءات',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'view.item': 'عرض العنصر',
    'remove.from.homepage': 'إزالة من الصفحة الرئيسية',
    'add.item.to.homepage': 'إضافة إلى الصفحة الرئيسية',
    'search.products': 'ابحث عن المنتجات...',
    'search.blog': 'ابحث عن المقالات...',
    'no.available.products': 'لا توجد منتجات متاحة.',
    'no.available.blog.posts': 'لا توجد مقالات متاحة.',
    'uncategorized': 'غير مصنف',
    'add': 'إضافة',
    'admin.add': 'إضافة',
    'admin.search': 'بحث',
    'admin.all': 'الكل',
    'admin.category': 'الفئة',
    'admin.price': 'السعر',
    'admin.availability': 'التوفر',
    'admin.actions': 'الإجراءات',
    'admin.uncategorized': 'بدون تصنيف',
    'admin.view': 'عرض',
    'admin.edit': 'تعديل',
    'admin.manage': 'إدارة',
    'admin.delete': 'حذف',
    'admin.basic_info': 'المعلومات الأساسية',
    'admin.name': 'الاسم',
    'admin.english': 'الإنجليزية',
    'admin.arabic': 'العربية',
    'admin.description': 'الوصف',
    'admin.select': 'اختر',
    'admin.specifications': 'المواصفات',
    'admin.image': 'صورة',
    'admin.alt_text': 'النص البديل',
    'admin.order': 'الترتيب',
    'admin.packages': 'الباقات',
    'admin.weight': 'الوزن',
    'admin.default': 'افتراضي',
    'admin.cancel': 'إلغاء',
    'admin.saving': 'جارٍ الحفظ...',
    'admin.update': 'تحديث',
    'admin.create': 'إنشاء',
    'admin.related': 'المنتجات المرتبطة',
     'admin.related2': 'المدونات المرتبطة',
    'admin.current': 'الحالية',
    'admin.no_data': 'لا توجد بيانات',
    'admin.similar': 'مماثل',
    'admin.complementary': 'مُكمل',
    'admin.product': 'المنتج',
    'admin.confirm_delete': 'تأكيد الحذف',
    'admin.delete_warning': 'لن تتمكن من استعادة هذا العنصر بعد الحذف.',
     'admin.products':'المنتجات',
    
    'categories.title': 'إدارة الفئات',
    'categories.add_category': 'إضافة فئة',
    'categories.search_placeholder': 'ابحث في الفئات...',
    'categories.table.name': 'الاسم',
    'categories.table.slug': 'المُعرّف',
    'categories.table.description': 'الوصف',
    'categories.table.created': 'تاريخ الإضافة',
    'categories.table.actions': 'الإجراءات',
    'categories.form.add_title': 'إضافة فئة',
    'categories.form.edit_title': 'تعديل الفئة',
    'categories.form.name_en': 'الاسم (إنجليزي)',
    'categories.form.name_ar': 'الاسم (عربي)',
    'categories.form.slug': 'المُعرّف',
    'categories.form.description_en': 'الوصف (إنجليزي)',
    'categories.form.description_ar': 'الوصف (عربي)',
    'categories.form.cancel': 'إلغاء',
    'categories.form.saving': 'جارٍ الحفظ...',
    'categories.form.update': 'تحديث',
    'categories.form.create': 'إنشاء',
    'categories.delete_modal.title': 'تأكيد الحذف',
    'categories.delete_modal.message': 'هل أنت متأكد أنك تريد حذف هذه الفئة؟ لا يمكن التراجع عن هذا الإجراء.',
    'categories.delete_modal.cancel': 'إلغاء',
    'categories.delete_modal.delete': 'حذف',
    'export.title': 'الدول المُصدّرة',
  'export.add': 'إضافة دولة',
  'export.search.placeholder': 'ابحث عن الدول...',
  'export.table.order': 'الترتيب',
  'export.table.country': 'الدولة',
  'export.table.exports': 'الصادرات السنوية',
  'export.table.products': 'المنتجات الرئيسية',
  'export.table.status': 'الحالة',
  'export.table.actions': 'الإجراءات',
  'export.status.active': 'نشطة',
  'export.status.inactive': 'غير نشطة',
  'export.edit': 'تعديل الدولة',
  'export.add_new': 'إضافة دولة مُصدّرة جديدة',
  'export.name_en': 'اسم الدولة (إنجليزي)',
  'export.name_ar': 'اسم الدولة (عربي)',
  'export.exports_en': 'الصادرات السنوية (إنجليزي)',
  'export.exports_ar': 'الصادرات السنوية (عربي)',
  'export.products_en': 'المنتجات الرئيسية (إنجليزي)',
  'export.products_ar': 'المنتجات الرئيسية (عربي)',
  'export.display_on_site': 'عرض على الموقع',
  'export.cancel': 'إلغاء',
  'export.create': 'إضافة',
  'export.update': 'تحديث',
  'export.saving': 'جاري الحفظ...',
  'export.delete.title': 'حذف الدولة',
  'export.delete.confirmation': 'هل أنت متأكد أنك تريد حذف هذه الدولة المُصدّرة؟ لا يمكن التراجع عن هذا الإجراء.',
  'export.delete': 'حذف',
    'blog.title': 'إدارة مقالات المدونة',
  'blog.add_post': 'إضافة مقال',
  'blog.search.placeholder': 'ابحث عن المقالات...',
  'blog.all_categories': 'كل الفئات',
  'blog.uncategorized': 'بدون تصنيف',
  'blog.table.post': 'المقال',
  'blog.table.category': 'الفئة',
  'blog.table.author': 'المؤلف',
  'blog.table.status': 'الحالة',
  'blog.table.date': 'التاريخ',
  'blog.table.actions': 'الإجراءات',
  'blog.status.published': 'منشور',
  'blog.status.draft': 'مسودة',
  'blog.modal.edit_post': 'تعديل المقال',
  'blog.modal.add_new_post': 'إضافة مقال جديد',
  'blog.modal.select_category': 'اختر الفئة',
  'blog.modal.cancel': 'إلغاء',
  'blog.modal.saving': 'جاري الحفظ...',
  'blog.modal.delete_title': 'حذف المقال',
  'blog.modal.delete_confirmation': 'هل أنت متأكد أنك تريد حذف هذا المقال؟ لا يمكن التراجع عن هذا الإجراء.',
  'blog.modal.delete': 'حذف',
  'blog.modal.view_post': 'عرض المقال',
  'blog.modal.edit_post_btn': 'تعديل المقال',
  'blog.modal.manage_related_posts': 'إدارة المقالات المرتبطة',
  'blog.modal.related_posts': 'المقالات المرتبطة الحالية',
  'blog.modal.add_related_posts': 'إضافة مقالات مرتبطة',
  'blog.modal.no_related_posts': 'لا توجد مقالات مرتبطة بعد.',
  'blog.modal.all_related': 'كل المقالات المتاحة مرتبطة بالفعل.',
  'blog.fields.title_en': 'العنوان (إنجليزي)',
  'blog.fields.title_ar': 'العنوان (عربي)',
  'blog.fields.slug': 'الرابط المختصر',
  'blog.fields.excerpt_en': 'الوصف المختصر (إنجليزي)',
  'blog.fields.excerpt_ar': 'الوصف المختصر (عربي)',
  'blog.fields.content_en': 'المحتوى (إنجليزي)',
  'blog.fields.content_ar': 'المحتوى (عربي)',
  'blog.fields.category': 'الفئة',
  'blog.fields.author_en': 'المؤلف (إنجليزي)',
  'blog.fields.author_ar': 'المؤلف (عربي)',
  'blog.fields.read_time_en': 'مدة القراءة (إنجليزي)',
  'blog.fields.read_time_ar': 'مدة القراءة (عربي)',
  'blog.fields.event_date_en': 'تاريخ الحدث (إنجليزي)',
  'blog.fields.event_date_ar': 'تاريخ الحدث (عربي)',
  'blog.fields.status': 'الحالة',
  'blog.fields.featured_image_url': 'رابط الصورة الرئيسية',
  'blog.relation_types.related': 'مرتبط',
  'blog.relation_types.similar': 'مشابه',
  'blog.relation_types.follow_up': 'متابعة',
    'blogCategories.title': 'فئات المدونة',
  'blogCategories.add': 'إضافة فئة',
  'blogCategories.search.placeholder': 'ابحث في فئات المدونة...',
  'blogCategories.table.name': 'الاسم',
  'blogCategories.table.slug': 'الاسم المختصر (Slug)',
  'blogCategories.table.created': 'تاريخ الإنشاء',
  'blogCategories.table.actions': 'الإجراءات',
  'blogCategories.edit.title': 'تعديل فئة المدونة',
  'blogCategories.addNew.title': 'إضافة فئة مدونة جديدة',
  'blogCategories.form.name_en': 'الاسم (إنجليزي)',
  'blogCategories.form.name_ar': 'الاسم (عربي)',
  'blogCategories.form.slug': 'الاسم المختصر (Slug)',
  'blogCategories.form.name_en.placeholder': 'اسم الفئة بالإنجليزية',
  'blogCategories.form.name_ar.placeholder': 'اسم الفئة بالعربية',
  'blogCategories.form.slug.placeholder': 'الاسم المختصر للفئة',
  'blogCategories.form.cancel': 'إلغاء',
  'blogCategories.form.create': 'إنشاء',
  'blogCategories.form.update': 'تحديث',
  'blogCategories.form.saving': 'جارٍ الحفظ...',
  'blogCategories.delete.title': 'حذف فئة المدونة',
  'blogCategories.delete.confirmation': 'هل أنت متأكد من حذف هذه الفئة؟ هذا الإجراء لا يمكن التراجع عنه.',
  'blogCategories.delete.cancel': 'إلغاء',
  'blogCategories.delete.delete': 'حذف',
   'contacts.title': 'رسائل الاتصال',
  'contacts.totalMessages': ' رسالة إجمالية',
  'contacts.search.placeholder': 'ابحث في الرسائل...',
  'contacts.filter.allStatus': 'كل الحالات',
  'contacts.filter.unread': 'غير مقروءة',
  'contacts.filter.read': 'مقروءة',
  'contacts.filter.responded': 'تم الرد',
  'contacts.table.contact': 'الاتصال',
  'contacts.table.subject': 'الموضوع',
  'contacts.table.status': 'الحالة',
  'contacts.table.date': 'التاريخ',
  'contacts.table.language': 'اللغة',
  'contacts.table.actions': 'الإجراءات',
  'contacts.status.unread': 'غير مقروءة',
  'contacts.status.read': 'مقروءة',
  'contacts.status.responded': 'تم الرد',
  'contacts.language.ar': 'العربية',
  'contacts.language.en': 'الإنجليزية',
  'contacts.action.viewDetails': 'عرض التفاصيل',
  'contacts.action.deleteMessage': 'حذف الرسالة',
  'contacts.details.title': 'تفاصيل رسالة الاتصال',
  'contacts.details.name': 'الاسم',
  'contacts.details.email': 'البريد الإلكتروني',
  'contacts.details.phone': 'الهاتف',
  'contacts.details.subject': 'الموضوع',
  'contacts.details.message': 'الرسالة',
  'contacts.details.status': 'الحالة',
  'contacts.details.dateReceived': 'تاريخ الاستلام',
  'contacts.details.close': 'إغلاق',
  'contacts.details.reply': 'الرد عبر البريد الإلكتروني',
  'contacts.delete.title': 'حذف رسالة الاتصال',
  'contacts.delete.confirmation': 'هل أنت متأكد من حذف هذه الرسالة؟ هذا الإجراء لا يمكن التراجع عنه.',
  'contacts.delete.cancel': 'إلغاء',
  'contacts.delete.delete': 'حذف',
   'admin.logout': 'تسجيل الخروج',
   'admin.welcome': 'مرحباً بك',
   'admin.dashboard': 'لوحة التحكم',
    'admin.last_updated': 'آخر تحديث',
    'admin.logo': 'مؤسسة الشمالي التجارية',
  }
};

// Merge admin translations with main translations
Object.keys(adminTranslations).forEach(lang => {
  translations[lang] = { ...translations[lang], ...adminTranslations[lang] };
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('ar');
  const [direction, setDirection] = useState<Direction>('ltr');

  useEffect(() => {
    // Load language from localStorage
    const savedLanguage = localStorage.getItem('Al-Shmaly -language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ar')) {
      setLanguageState(savedLanguage);
      setDirection(savedLanguage === 'ar' ? 'rtl' : 'ltr');
    }
  }, []);

  useEffect(() => {
    // Update document direction and font
    document.documentElement.dir = direction;
    document.documentElement.lang = language;
    
    // Add/remove Arabic font class
    if (language === 'ar') {
      document.documentElement.classList.add('font-arabic');
    } else {
      document.documentElement.classList.remove('font-arabic');
    }
  }, [language, direction]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    setDirection(lang === 'ar' ? 'rtl' : 'ltr');
    localStorage.setItem('Al-Shmaly -language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const getLocalizedField = (data: any, field: string): string => {
    if (!data) return '';
    
    const localizedField = language === 'ar' ? `${field}_ar` : field;
    const fallbackField = language === 'ar' ? field : `${field}_ar`;
    
    return data[localizedField] || data[fallbackField] || data[field] || '';
  };

  return (
    <LanguageContext.Provider value={{
      language,
      direction,
      setLanguage,
      t,
      getLocalizedField
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 